### ISSUE TITLE
Hi I have a question

### ISSUE THREAD

**Issue by slowcode42** [0vercl0k/z3-playground#1]
from z3 import *

a, b = BitVecs('a b', 32)
c, d = Ints('c d')
solve(a + b == 1337)
solve(c + d == 1337)

s = Solver()
s.add(a + b == 1337)
print s.check()
print s.model()

s = Solver()
s.add(c + d == 1337)
print s.check()
print s.model()

s = Solver()
s.add(a + b == 1337)
s.push()
s.add(a*a == 32)
print s
print s.check()

s.pop()
print s
print s.check()
print s.model()
print (469762080 + 3825206553) & 0xffffffff
  ====================================
root@ubuntu:~/z3-playground/essentials# python test.py 
[b = 0, a = 1337]
[d = 0, c = 1337]
sat
[b = 0, a = 1337]
sat
[d = 0, c = 1337]
[a + b == 1337, a*a == 32]
unsat
[a + b == 1337]
sat
[b = 469762080, a = 3825206553]
1337
  ====================================
my test result show me that push&pop operation affect to result.

but It's not what I want. How can I fix it?

**Comment by 0vercl0k** [comment]
Hello,
Every single solution that solver/Solver can generate should be treated equally ; they will all satisfy your constraints. So you have no guaranties that two calls to solve with the same constraints will give you the same result. You are free to add more constraints if you want to eliminate specific ones.

Does that make sense?

**Comment by slowcode42** [comment]
ah I see. thanks for the reply :)

**Comment by 0vercl0k** [comment]
No worries! :-)
