### ISSUE TITLE
Hi! may I have a question?

### ISSUE THREAD

**Issue by slowcode42** [0vercl0k/z3-playground#2]
can you give hint me why case2 doesn't work??

root@ubuntu:/root# cat test.py
# !/usr/bin/env python

from z3 import *
# CASE1

key = BitVec("tag", 32)
solve(RotateRight(key, 7) == 0x9a000000)
# CASE2

tag = BitVec("tag", 32)
key = BitVecVal(0, 32)
key = key + tag
RotateRight(key, 7)
solve(key == 0x9a000000, tag == 77)
root@ubuntu:/root# ./test.py 
[tag = 77]
no solution

**Comment by 0vercl0k** [comment]
Sure, in the case n°2 you don't keep track of the Rotation you are applying
on key ; so the line "RotateRight(key, 7)" is useless.
Try to replace it by: "key = RotateRight(key, 7)" and it should work!

Cheers,
0vercl0k

2015-01-21 5:02 GMT+00:00 hdarwin notifications@github.com:

**Comment by slowcode42** [comment]
ahha! thanks a lot! and thanks for your secday presetation! :+1:

**Comment by 0vercl0k** [comment]
No worries :-)

2015-01-21 10:51 GMT+00:00 hdarwin notifications@github.com:
