### ISSUE TITLE
Why is it that BitVec is much faster than Int?

### ISSUE THREAD

**Issue by 0xGodspeed** [0vercl0k/z3-playground#6]
https://github.com/0vercl0k/z3-playground/blob/9496201c9a21e8f0ff43015af2527b69018b73ee/magic_square_z3.py#L36-L39

Apologies if this is not the correct place to ask such questions.

**Comment by 0vercl0k** [comment]
I am not an expert - but my understanding is that an Int is more like an
integer in mathematics; it isn't bounded by a number of bits or anything
(could be infinite, etc.). At least this is my understanding :)

Cheers
